API_BASE_URL = "https://jobcoin.gemini.com/deputize-green/api"
API_ADDRESS_URL = "{}/addresses".format(API_BASE_URL)
API_TRANSACTIONS_URL = "{}/transactions".format(API_BASE_URL)

HOUSE_ADDRESS = "Lucia"

WITHDRAWAL_INCREMENT = 2.5
FIRST_WITHDRAWAL_ADDRESS_INDEX = 0

DISTRIBUTE_DEPOSITS_INTERVAL_SEC = 5.0
GET_NEW_DEPOSITS_INTERVAL_SEC = 10.0
